apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  labels:
    app: homework
    ver: v1
spec:
  containers:
  - name: web
    image: lucho3/homework-3
    ports:
      - containerPort: 80
    